import{a as E,S as q,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function m(t,o){const n="52793132-8c92efb256d235a72d9068fff",s="https://pixabay.com/api/",e={key:n,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await E.get(s,{params:e})).data}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
            <li class="gallery-item">
                <a href="${s}">
                    <img src="${n}" alt="${e}" />
                </a>
                <div class="info">
                    <p><b>Likes:</b> ${r}</p>
                    <p><b>Views:</b> ${i}</p>
                    <p><b>Comments:</b> ${S}</p>
                    <p><b>Downloads:</b> ${v}</p>
                </div>
            </li>
        `).join("");h.insertAdjacentHTML("beforeend",o),P.refresh()}function $(){h.innerHTML=""}function b(){p.classList.remove("is-hidden")}function L(){p.classList.add("is-hidden")}function B(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}const f=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let l="",c=1,d=0;const R=15;f.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}l=o,c=1,$(),u(),b();try{const n=await m(l,c);if(d=n.totalHits,n.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(n.hits),w()}catch(n){a.error({title:"Error",message:`Something went wrong: ${n.message}`,position:"topRight"})}finally{L(),f.reset()}});M.addEventListener("click",async()=>{c++,b(),u();try{const t=await m(l,c);y(t.hits),x(),w()}catch(t){a.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight"})}finally{L()}});function w(){const t=Math.ceil(d/R);c>=t?(u(),d>0&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):B()}function x(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
